version: "2.13"
services:
  frontend:
    build:
      context: "./client"
      dockerfile: Dockerfile.dev
    image: weebid-react-client:v1
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - "./client:/usr/src/app"
  backend:
    build:
      context: "./server"
      dockerfile: Dockerfile.dev
    image: weebid-node-server:v1
    ports:
      - "3001:3001"
    volumes:
      - "./server:/usr/src/app"
    depends_on:
      - db
  db:
    image: mari-a-db
    restart: always
    ports:
      - 6033:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: root
      MYSQL_DATABASE: weebid_react
    volumes:
      - mariadb-data:/data/db
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306 
    depends_on:
      - db
volumes:
  mariadb-data:
    driver: local
