version: "2.13"
services:
  frontend:
    build:
      context: "./client"
      dockerfile: Dockerfile.dev
    image: weebid-react-client:v1
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - communication-medium
    volumes:
      - "./client:/usr/src/app"
  backend:
    build:
      context: "./server"
      dockerfile: Dockerfile.dev
    image: weebid-node-server:v1
    ports:
      - "3001:3001"
    networks:
      - communication-medium
    volumes:
      - "./server:/usr/src/app"
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    networks:
      - communication-medium
    ports:
      - 6033:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: weebid_react
    volumes:
      - mysql-data:/data/db
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - db
networks:
  communication-medium:
    driver: bridge
volumes:
  mysql-data:
    driver: local
